### PR TITLE
Adds Tethys Portal project description

### PR DESCRIPTION
**Pull request by swainn**

### CODE REVIEW

**Comment by swainn** [comment]
I'd like to have Dan Ames review before this is merged.

**Review by arpita0911patel — APPROVED** [review]
Looks good. Approving it.

**Comment by arpita0911patel** [comment]
> I'd like to have Dan Ames review before this is merged.

Ya, sure. Will wait on that. Thank you Nathan.

**Comment by swainn** [comment]
@arpita0911patel this is ready to go!

**Pull request merged**
